### ISSUE TITLE
passing json object to mobile service client.login gives json error

### ISSUE THREAD

**Issue by nvasilescu** [Azure/azure-mobile-apps-android-client#19]
"com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 12 path $"

mClient.login reaches onFailure with this error. You can replace the access_token with any strings. The login will fail with json syntax exception.

JsonObject body = new JsonObject();
body.addProperty("access_token", token.trim());

ListenableFuture<MobileServiceUser> mLogin = mClient.login(MobileServiceAuthenticationProvider.Facebook,body);

        Futures.addCallback(mLogin, new FutureCallback<MobileServiceUser>() {
            @Override
            public void onFailure(Throwable exc) {
                Log.d(TAG , "fb login fail" + exc.getCause() + " / " + exc.getMessage());
             
            }

            @Override
            public void onSuccess(MobileServiceUser user) {
                Log.d(TAG , "fb login succes " + user.getUserId() + " /"  + user.getAuthenticationToken());
              
            }
        });

**Comment by soninaren** [comment]
@nvasilescu
I was unable to reprocude the issue. I tested with the mention Json object. The only exception i ran into was authentication failure because I changed the access token on the Json Object otherwise i got successful results. The json object i used for successful runs is below.

{"access_token":"<token>"}
