### ISSUE TITLE
Operator IN instead of foreach()

### ISSUE THREAD

**Issue by Guimareshh** [Azure/azure-mobile-apps-android-client#57]
Hi everyone,

I'm trying to optimize the way I'm getting data from Azure Server with Azure Mobile Service. Indeed, I want to get a list of **Customer** by a list of **idCustomer**. For now, I'm using a foreach(), but it's really slow because I'm making a MobileService request for each **idCustomer**. Moreover I need to get a list of product attached to a customer.

Is there a way, like the IN operator in SQL, to insert a list of values with one request ? Check the above example
```sql

SELECT firstname
FROM user
WHERE firstname IN ( 'Maurice', 'Marie', 'Thimoté' )
```

Here is what I'm doing for now in Android:
```java
for (int idCustomer : idCustomerList) {
                customerList.addAll(customerTable.where().field("id").eq(idCustomer).top(1000).execute().get());

                int itemsToSkip = 0;
                do {
                    productList.addAll(productTable.where().field("IdCustomers").eq(idCustomer).skip(itemsToSkip).top(1000).execute().get());
                    itemsToSkip = itemsToSkip + 1000;
                }
                while(productList.size() !=0 && productList.size() % 1000 == 0);
            }
```

Top is set to 1000 for customer, because it's the limit set. For products, we can have more than 1000 products. That's why I'm doing like this.

**Comment by lindydonna** [comment]
The reason this isn't possible right now is because we don't directly support relationships between tables, but it is an area we are investigating.

If the list of customers to retrieve is relatively small (<100 or so), then you can pass it to the server as part of a where query, essentially constructing a query that contains your list of customers, rather than one query per customer. 

Otherwise, I recommend that you create a custom API where you can pass in the list of customers. Better yet, is there a way that the server can get the list of customers based on another query?  For instance, maybe you want all customers in a region, so you could pass a query parameter to your server script to do that filtering, or use a custom API.

If you want more than 1000 products, I recommend that you use offline sync, so that you can store all of the results on the client and not have to do the query each time. In that case, the client SDK will automatically do multiple requests in order to get all of the results.

**Comment by Guimareshh** [comment]
Hi @lindydonna,

Thanks for your reply !

I'm really surprised you don't support relationships between tables, I have never seen a word about that in the documentation.

I will check the documentation for the offline sync. Because are using a local database in our Android app, I'm not sure it will fit our need to use the offline sync.

I'm closing the issue.
