### ISSUE TITLE
Query parameters are duplicated in URL

### ISSUE THREAD

**Issue by olehb007** [Azure/azure-mobile-apps-android-client#90]
After migrating project from Azure mobile services I've found all queries have duplicated parameters as they are added in 2 places: 
* mobileservices\table\MobileServiceJsonTable.java
List<Pair<String, String>> userParameters = query.getUserDefinedParameters();
* mobileservices/table/query/QueryODataWriter.java
List<Pair<String, String>> parameters = query != null ? query.getUserDefinedParameters() : null;

**Comment by dhei** [comment]
I've replied @olehb007 privately via email a week ago. Let me post it here. I don't see how they duplicate because the code in MobileServiceJsonTable is only adding a MobileServiceFeatures.AdditionalQueryParameters to the features EnumSet that got used in request header, not adding anything to the actual query string. 

I am closing this. Let me know if you have a repro of this.
