### ISSUE TITLE
onActityResult never gets called if user is already signed into google

### ISSUE THREAD

**Issue by arkum** [Azure/azure-mobile-apps-android-client#97]
I am trying to implement google authentication in my android app which is connecting to an Azure Mobile service (app). I am calling MobileServiceClient.login method in the onCreate method of the activity.

`_client.login("Google","{url_scheme}",1) `

If i am already logged into google the `onActityResult `never gets called until i bring the up to the foreground manually. If I log out of the google account in the browser and relaunch the app, the authentication dialog will prompt me for the email and password and after successful sign in `onActivityResult `is called.

I have configured the RedirectUrlActivity in the app manifest

```
<activity android:launchMode="singleTop" android:name="com.microsoft.windowsazure.mobileservices.authentication.RedirectUrlActivity">
        <intent-filter>
            <action android:name="android.intent.action.VIEW"/>

            <category android:name="android.intent.category.DEFAULT"/>
            <category android:name="android.intent.category.BROWSABLE"/>

            <data android:scheme="{url_scheme}"
                android:host="easyauth.callback"
                />
        </intent-filter>
    </activity>

```
Dependencies for the customtabs library is also in place

`compile 'com.android.support:customtabs:25.3.1'`
I am using android sdk version 25 and mobile services sdk 3.3

`compile 'com.microsoft.azure:azure-mobile-android:3.3.0@aar'`

I tested this with the default google sign on API. `onActityResult ` gets called and app doesn't go to background. Looks like an issue with the invocation of startActivityForResult inside the mobile service SDK

**Comment by MatkovIvan** [comment]
Hi @arkum 
Sorry for the long delay.

I've checked both scenarios with Android SDK `25` and `26` on different devices with different Android versions, but couldn't reproduce the issue. Please, double check that you completed all steps in [the documentation](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-android-get-started-users), including setup server side in the Azure portal. Also please check that your `"{url_scheme}"` is unique: second application with same scheme doesn't installed on the test device.
If all looks right and it still happens, could you please try to reproduce it on sample application?

Let me know if this issue is still relevant.
Thanks,
Ivan

**Comment by elamalani** [comment]
@arkum Were you able to fix this issue in your application? Please let us know if you need any help from the product team. Thanks!

**Comment by elamalani** [comment]
@arkum We haven't heard back from you. I'm closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!

**Comment by arkum** [comment]
Sorry guys, missed the notification mails about this. I have solved the problem using the google sign on API. never tested the mobile service Api after that. good to close. thanks for following up
