### ISSUE TITLE
SDK converts Column Names to lower case

### ISSUE THREAD

**Issue by icsd** [Azure/azure-mobile-apps-android-client#98]
Why does the SDK convert the column names of the tables to lower case?
This creates problems if you want to have camel case names for the columns.

**Comment by bmourat** [comment]
Hi @icsd 
Sorry for late response. You can use camel case column names, just decorate your field with annotation for serialization:
```
@com.google.gson.annotations.SerializedName("ItemStatus")
private String status;
```

**Comment by elamalani** [comment]
@icsd We haven't heard back from you. I'm closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!

**Comment by MatkovIvan** [comment]
Hi @icsd ,

Could you please elaborate more what case exactly doesn't work for you?
For me, it looks like this is detail of implementation that shouldn't affect public API behaviour of the SDK.

**Comment by icsd** [comment]
It does not create a bug or issue..It is just a not convenient implementation because you can not have exaclty the same column names on the backend and the Android client.
For example when you parse a field (e.g. `itemStatus`) from a request you can have it declared 
 as `@com.google.gson.annotations.SerializedName("itemStatus")`, but when you make a query to the local DB and want this column you have to `SELECT` it as `itemstatus` because this is how it is normalized in the DB table from the Azure SDK.
In the iOS Azure SDK this column name normalization does not happen.
These are the reasons I was wondering why this happens. 
Thank you for your response.

**Comment by MatkovIvan** [comment]
OK, got it. Thanks for reporting this. I agree that it should be consistent with other platforms.
Regarding reasons - it's really hard to say that now. It was added in 2014 and hasn't been changed since that.
I'm afraid we aren't going to change it because it's a breaking change and requires migration/renaming in existing DBs at least.
If it's important for you, you can try to drop this conversion in your fork, but since it's just inconsistency and doesn't cause any errors - I'd keep it as is in this repo.
